"""empty message

Revision ID: 689293ce46cb
Revises: e0f4f2edf3b4
Create Date: 2017-02-06 01:59:21.302423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689293ce46cb'
down_revision = 'e0f4f2edf3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('img_url', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'img_url')
    # ### end Alembic commands ###
